# Generated by Django 5.0.6 on 2024-06-18 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_elements', '0001_initial'),
        ('meetings', '0002_remove_meeting_access_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('text_question', 'Открытый вопрос (текст)'), ('number_question', 'Открытый вопрос (число)'), ('audience_qa', 'Audience Q&A'), ('networking', 'Нетворкинг'), ('star_voting', 'Экспресс-голосование (звёздочки)'), ('single_choice', 'Экспресс-голосование (Single-choice)'), ('multiple_choice', 'Экспресс-голосование (Multiple choice)'), ('survey', 'Опрос по небольшой анкете'), ('quiz', 'Викторина')], max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_repeatable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactives', to='meetings.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interactive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interactive_elements.interactive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('options', models.JSONField()),
                ('interactive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice', to='interactive_elements.interactive')),
            ],
        ),
        migrations.CreateModel(
            name='Networking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_duration', models.PositiveIntegerField(default=5)),
                ('interactive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='networking', to='interactive_elements.interactive')),
            ],
        ),
        migrations.CreateModel(
            name='NumberQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(default=0)),
                ('max_value', models.FloatField(default=100)),
                ('interactive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='number_question', to='interactive_elements.interactive')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField()),
                ('interactive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='interactive_elements.interactive')),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('options', models.JSONField()),
                ('interactive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='single_choice', to='interactive_elements.interactive')),
            ],
        ),
        migrations.CreateModel(
            name='StarVoting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_stars', models.PositiveIntegerField(default=5)),
                ('interactive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='star_voting', to='interactive_elements.interactive')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField()),
                ('interactive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='interactive_elements.interactive')),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_length', models.PositiveIntegerField(default=1000)),
                ('interactive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_question', to='interactive_elements.interactive')),
            ],
        ),
        migrations.DeleteModel(
            name='InteractiveElement',
        ),
        migrations.AddField(
            model_name='audienceqa',
            name='interactive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience_qa', to='interactive_elements.interactive'),
        ),
    ]
