# Generated by Django 5.0.6 on 2024-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_elements', '0002_audienceqa_interactive_interactiveresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='singlechoice',
            name='question',
        ),
        migrations.AddField(
            model_name='audienceqa',
            name='question_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='question_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='networking',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='numberquestion',
            name='question_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singlechoice',
            name='question_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='starvoting',
            name='question_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='question_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
