# Generated by Django 5.0.6 on 2024-06-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_elements', '0003_remove_multiplechoice_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audienceqa',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_qa', to='interactive_elements.interactive'),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice', to='interactive_elements.interactive'),
        ),
        migrations.AlterField(
            model_name='networking',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networking', to='interactive_elements.interactive'),
        ),
        migrations.AlterField(
            model_name='numberquestion',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_question', to='interactive_elements.interactive'),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_choice', to='interactive_elements.interactive'),
        ),
        migrations.AlterField(
            model_name='starvoting',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_voting', to='interactive_elements.interactive'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_question', to='interactive_elements.interactive'),
        ),
    ]
