# Generated by Django 5.0.6 on 2024-06-21 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_elements', '0004_alter_audienceqa_interactive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoice',
            name='interactive',
        ),
        migrations.RemoveField(
            model_name='singlechoice',
            name='interactive',
        ),
        migrations.RemoveField(
            model_name='starvoting',
            name='interactive',
        ),
        migrations.AddField(
            model_name='quiz',
            name='game_type',
            field=models.CharField(choices=[('five_facts', '5 фактов'), ('thematic_quizzes', 'Тематические квизы'), ('association_game', 'Игра в ассоциации: три варианта'), ('unexpected_ending', 'История с неожиданным концом')], default='five_facts', max_length=100),
        ),
        migrations.AlterField(
            model_name='audienceqa',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_qas', to='interactive_elements.interactive'),
        ),
        migrations.AlterField(
            model_name='networking',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networkings', to='interactive_elements.interactive'),
        ),
        migrations.AlterField(
            model_name='numberquestion',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_questions', to='interactive_elements.interactive'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_questions', to='interactive_elements.interactive'),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, default='')),
                ('options', models.JSONField()),
                ('max_choices', models.PositiveIntegerField(default=1)),
                ('interactive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_questions', to='interactive_elements.interactive')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interactive_elements.multiplechoicequestion')),
            ],
        ),
        migrations.CreateModel(
            name='NumberAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_number', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interactive_elements.numberquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interactive_elements.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, default='')),
                ('options', models.JSONField()),
                ('interactive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_choice_questions', to='interactive_elements.interactive')),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interactive_elements.singlechoicequestion')),
            ],
        ),
        migrations.CreateModel(
            name='StarVotingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, default='')),
                ('max_stars', models.PositiveIntegerField(default=5)),
                ('interactive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_voting_questions', to='interactive_elements.interactive')),
            ],
        ),
        migrations.CreateModel(
            name='StarVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='interactive_elements.starvotingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, default='')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='interactive_elements.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interactive_elements.surveyquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interactive_elements.textquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InteractiveResponse',
        ),
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
        migrations.DeleteModel(
            name='SingleChoice',
        ),
        migrations.DeleteModel(
            name='StarVoting',
        ),
    ]