# Generated by Django 5.0.6 on 2024-06-11 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название встречи')),
                ('description', models.TextField(blank=True, verbose_name='Описание встречи')),
                ('url', models.URLField(verbose_name='URL встречи')),
                ('start_time', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('access_level', models.CharField(choices=[('public', 'Публичная'), ('private', 'Частная')], default='public', max_length=50, verbose_name='Права доступа')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Хост')),
            ],
        ),
    ]
